### ISSUE TITLE
Feature Request - Card for remotes, media_players 

### ISSUE THREAD

**Issue by jer78** [ciotlosm/docs-lovelace#12]
Sorry if this is the wrong place. Not sure where to leave requests. But wondering if you can make a remote card glance that changes the media_player based on the remote activity for use with something like Harmony remotes. And the activities in the remote would be icons like in the picture-glance card. 

Or another suggestion would be to make a dynamic media player based on a template and we could add template switches to change the media player.

Finally, if it’s possible to add the volume controls directly in a media card I would be eternally grateful!

**Comment by ciotlosm** [comment]
Can you please post your issue here: https://github.com/home-assistant/ui-schema/issues ?
