### ISSUE TITLE
problem with card

### ISSUE THREAD

**Issue by vMeph** [ciotlosm/docs-lovelace#13]
hi i dont know if this the correct place to post this, but im wondering if this a problem with the card im using or some bug
its a component im using for track packages using aftership, im using component from here
https://github.com/tr1plus/ha-aftership
now the problem is on the normal frontend i see like this witch is correct
![1](https://user-images.githubusercontent.com/12812111/42415517-144d813a-8249-11e8-9ef4-6b1a00c8931f.jpg)
on lovelace i see like this
![2](https://user-images.githubusercontent.com/12812111/42415518-212734be-8249-11e8-8873-1019353fd867.jpg)
if i click on it then i see like this
![3](https://user-images.githubusercontent.com/12812111/42415520-2d1d6914-8249-11e8-985a-24000a50333b.jpg)
i have  tryed with all cards and the way it shows is like the 2th pic
any ideas how to make it , to see like first pic?

thanks

**Comment by ciotlosm** [comment]
Your setup is using a custom UI. Better ask on the repo: https://github.com/tr1plus/ha-aftership for an update to work with lovelace.
