### ISSUE TITLE
Problem with redirect to Lovelace

### ISSUE THREAD

**Issue by edoardop13** [ciotlosm/docs-lovelace#14]
I deleted all the data related to the site (cookies, cache), but from 2 of my phones, honor6x and redmi note 4 with google chrome  lovelace not redirect, and from the url I verified that there is always /states.
This error appears in the log file:

https://xxx.duckdns.org/local/lovelace.html:2:112 Uncaught TypeError: Cannot read property 'shadowRoot' of null

**Comment by ciotlosm** [comment]
I will have a look tonight and fix the errors. Seems in some cases that JS is not working as it should. 

Keep in mind that the use of the hack should be only to avoid going to /status when clicking overview. 

To just get lovelace to load first when accessing / can be done from the UI

**Comment by ciotlosm** [comment]
@httpedo13 it seems this is no longer necessary. Starting with HA 0.73.1 Overview will point to Lovelace once you set it as default.
